blueprint:
  name: KNX → Home Assistant Scene
  description: >
    Bind a KNX Scene GA (DPT 18.001) to a Home Assistant scene.
    KNX → HA: on KNX scene recall, activate the HA scene (ignores learn).
    HA → KNX: when the HA scene is turned on, mirror a KNX recall to the GA.
    No loop because the KNX trigger uses outgoing: false.
  domain: automation
  author: remus-gpt

  input:
    knx_scene_address:
      name: KNX Scene Group Address
      description: KNX GA that sends the scene recall (e.g., 1/2/3).
      default: ""
    knx_scene_number:
      name: KNX Scene Number
      description: The specific scene number (1-64) to trigger this automation.
      selector:
        number:
          min: 1
          max: 64
          mode: box
    ha_scene:
      name: Home Assistant Scene
      description: The HA scene to activate when the KNX scene is recalled.
      selector:
        entity:
          domain: scene

mode: single
max_exceeded: silent

variables:
  v_knx_scene_number: !input knx_scene_number
  v_ha_scene: !input ha_scene
  v_knx_address: !input knx_scene_address

trigger:
  # KNX → HA (only incoming bus writes; ignores our own sends)
  - id: knx_in
    platform: knx.telegram
    destination: !input knx_scene_address
    outgoing: false
    group_value_read: false
    group_value_response: false

  # HA → KNX (whenever the selected HA scene is turned on)
  - id: ha_scene_on
    platform: event
    event_type: call_service
    event_data:
      domain: scene
      service: turn_on

condition: []

action:
  - choose:

      # ===== KNX → HA =====
      - conditions:
          - condition: template
            value_template: "{{ trigger.id == 'knx_in' }}"
          - condition: template
            value_template: "{{ trigger.dpt_main == 18 }}"
          - condition: template
            value_template: "{{ trigger.telegramtype == 'GroupValueWrite' }}"
          - condition: template
            value_template: >
              {{ (trigger.value is not defined)
                 or (trigger.value.learn is not defined)
                 or (trigger.value.learn == false) }}
          - condition: template
            value_template: >
              {{ trigger.value is defined
                 and trigger.value.scene_number is defined
                 and trigger.value.scene_number == v_knx_scene_number }}
        sequence:
          - service: scene.turn_on
            target:
              entity_id: !input ha_scene

      # ===== HA → KNX =====
      - conditions:
          # Only mirror user/API initiated calls; skip automation-originated ones
          - condition: template
            value_template: >
              {{ trigger.event.context is defined
               and trigger.event.context.user_id is not none
               and trigger.event.context.parent_id is none }}
 
          - condition: template
            value_template: >
              {% set sd = trigger.event.data.service_data if trigger.id == 'ha_scene_on' else {} %}
              {% set e = sd.entity_id %}
              {{ trigger.id == 'ha_scene_on'
                 and (
                      (e is string and e == v_ha_scene)
                      or (e is list and (v_ha_scene in e))
                 ) }}
        sequence:
          # DPT 18.001: 1 byte. bit6=learn (0), bits0..5 = (scene_number - 1)
          - service: knx.send
            data:
              address: !input knx_scene_address
              # DPT 18.001 recall: payload = scene_number - 1
              payload: "{{ (v_knx_scene_number | int) - 1 }}"